### ISSUE TITLE
converting gbif occurrence.txt with dwc2parquet fails 

### ISSUE THREAD

**Issue by jhpoelen** [idigbio-api-hackathon/idigbio-spark#1]
A 2015 copy of gbif occurrence.txt (with "no geospatial issues") with a size of 332G was attempted to be converted to parquet format for more efficient storage and access using the dwc2parquet spark job. The job was executed on a single node mesos cluster using the mesos spark dispatcher framework. 

After several hours, the spark job fails. See attached dispatcher framework and driver logs.
[gbif_run_2016_02_26_driver_stderr_snip.txt](https://github.com/idigbio-api-hackathon/idigbio-spark/files/149500/gbif_run_2016_02_26_driver_stderr_snip.txt)
[gbif_run_2016_02_26_framework_stderr_snip.txt](https://github.com/idigbio-api-hackathon/idigbio-spark/files/149501/gbif_run_2016_02_26_framework_stderr_snip.txt)

**Comment by danstoner** [comment]
in gbif_run_2016_02_26_framework_stderr_snip.txt:

```
16/02/27 00:57:15 INFO HadoopRDD: Input split: file:/home/int/data/gbif/occurrence.txt:239779971072+33554432
16/02/27 00:57:18 ERROR Executor: Exception in task 7139.0 in stage 0.0 (TID 7139)
java.io.IOException: No space left on device
```

**Comment by jhpoelen** [comment]
Thanks @danstoner ! Turned out that Apache Mesos was using a /tmp folder on a smallish volume. Have since moved configured mesos to use a volume that @godfoder provided some time ago. hundreds of millions of records are being runching as I write using the new config . . . time will tell whether the ~TB volume is enough space for spark to breathe.

**Comment by jhpoelen** [comment]
gbif has been successfully converted into parquet file format, making it more efficient to be processed by using spark.

The 332GB idigbio occurrence.txt (uncompressed) resulted in 55G parquet files. 

Using spark-shell:
```
scala> val gbif = sqlContext.read.format("parquet").load("/home/int/data/gbif/occurrence.txt.parquet")
scala> gbif.count
...
res1: Long = 471538061
scala> 
```
in less than a minute.
